(define-module (www pages login)
  #:use-module (www pages)
  #:use-module (www config)
  #:use-module (www util)
  #:use-module (www db connections)
  #:use-module (www db overview)
  #:use-module (www db sessions)
  #:use-module (sparql driver)
  #:use-module (web response)
  #:use-module (ldap authenticate)
  #:use-module (ice-9 receive)
  #:use-module (ice-9 rdelim)
  #:use-module (srfi srfi-1)
  #:export (page-login))

(define* (page-login request-path #:key (post-data ""))
  (if (string= post-data "")
      ;; Handle non-POST requests.
      (let ((number-of-endpoints (length (all-connections))))
        (page-empty-template "Log in" request-path
         `((div (@ (id "login-wrapper"))
                (form (@ (action "/login") (method "POST"))
                      (input (@ (type "text")
                                (class "login-field")
                                (name "username")
                                (placeholder "Username")))
                      (input (@ (type "password")
                                (class "login-field")
                                (name "password")
                                (placeholder "Password")))
                      (input (@ (class "login-field")
                                (type "submit")
                                (value "Log in"))))))))
      ;; Handle POST-requests.
      ;; When we get here, the login as failed, because otherwise the
      ;; page handler would've redirected us already.
      (let ((data (post-data->alist post-data)))
        (page-empty-template "Log in" request-path
         `((div (@ (id "login-wrapper"))
                (div (@ (class "message-box failure"))
                     (p "Authentication failed."))
                (form (@ (action "/login") (method "POST"))
                      (input (@ (type "text")
                                (class "login-field")
                                (name "username")
                                (placeholder "Username")))
                      (input (@ (type "password")
                                (class "login-field")
                                (name "password")
                                (placeholder "Password")))
                      (input (@ (class "login-field")
                                    (type "submit")
                                    (value "Log in"))))))))))
